### ISSUE TITLE
Add option to disable input.

### ISSUE THREAD

**Issue by kingllama** [react-tags/react-tags#194]
There's a `readOnly` property right now, but it would be great to be able to `disable` the input.

**Comment by sjsn** [comment]
+1 I need closable tags without the input.

**Comment by ad1992** [comment]
@kingllama would you give a PR for this feature ?

**Comment by kingllama** [comment]
@ad1992 No promises but I can definitely take a look this weekend. My react skills and free time have certainly improved since I opened the issue.

**Comment by ad1992** [comment]
@sjsn I am sorry I didn't get you what you need. Can you please explain ?

**Comment by sjsn** [comment]
@ad1992 The pull request kingllama made addresses what I needed. Thanks!

**Comment by dmossie** [comment]
@ad1992 Was this ever implemented? This would be a great feature to have

**Comment by ad1992** [comment]
@dmossie there was a PR but the pr was not merged as some fixes were left in it.  Here is the PR https://github.com/prakhar1989/react-tags/pull/296

**Comment by atiqueansari1987** [comment]
@ad1992 I will try and submit PR this weekend.

**Comment by ad1992** [comment]
closed via #726, this will be available in next version 🎉
