### ISSUE TITLE
IE -> Expected "spec" provided as the second argument to DragSource to be a plain object. Instead, received [object Array Iterator]. Read more: http://react-dnd.github.io/react-dnd/docs-drag-source.html

### ISSUE THREAD

**Issue by tobiaskiel** [react-tags/react-tags#212]
Unalbe to use this in IE, I get the following error:
Expected "spec" provided as the second argument to DragSource to be a plain object. Instead, received [object Array Iterator]. Read more: http://react-dnd.github.io/react-dnd/docs-drag-source.html

npm ls gives:
+-- react-tag-input@4.7.2
| +-- lodash@4.15.0 deduped
| +-- prop-types@15.6.0 deduped
| +-- react-dnd@2.5.4
| | +-- disposables@1.0.1
| | +-- dnd-core@2.5.4
| | | +-- asap@2.0.6 deduped
| | | +-- invariant@2.2.2 deduped
| | | +-- lodash@4.15.0 deduped
| | | `-- redux@3.7.2
| | |   +-- lodash@4.15.0 deduped
| | |   +-- lodash-es@4.17.4
| | |   +-- loose-envify@1.3.1 deduped
| | |   `-- symbol-observable@1.0.4
| | +-- hoist-non-react-statics@2.3.1
| | +-- invariant@2.2.2 deduped
| | +-- lodash@4.15.0 deduped
| | `-- prop-types@15.6.0 deduped
| `-- react-dnd-html5-backend@2.5.4
|   `-- lodash@4.15.0 deduped

**Comment by ad1992** [comment]
@tobiaskiel is this issue happening in v5.0.1 ?
