### ISSUE TITLE
Swap layout of input and tags - display input on top

### ISSUE THREAD

**Issue by LaurieSReynolds** [react-tags/react-tags#233]
Really great component!  Thank you!

For an application that I'm building, the user may enter 30 or more tags.   

Is there a way to display the input control on the top and the tags below it?

I'm setting {inline=false} which displays the input box below the tags which is helpful.

**Comment by mrdannael** [comment]
AFAIK I don't think so. But that enhancement should not be difficult to add. I'll think about it :)

**Comment by LaurieSReynolds** [comment]
Cool.  Thank you!

**Comment by Napkutya** [comment]
Cool stuff! Thanks!

But I'm also interested in the swapping
now it looks like :
<ReactTags                                             
                                placeholder="Kulcsszavak: több tag esetén kérem vesszővel válassza el"                                                      
                                handleDelete={this.handleDelete}
                                handleAddition={this.handleAddition }
                                handleInputChange={this.onTagInputChange }  
                                handleDrag ={this.handleDrag}     
                                key={this.state.tags.join(",")}
                                tags={this.state.tags}                                                                                                  
                            />
please help me how can i swap :)

**Comment by ad1992** [comment]
This will be live once https://github.com/prakhar1989/react-tags/pull/346 is merged

**Comment by ronmara** [comment]
I’m trying to implement it too now, is there a way already?

**Comment by ad1992** [comment]
closed via #491
