### ISSUE TITLE
cannot edit the tags?

### ISSUE THREAD

**Issue by imjay009** [react-tags/react-tags#375]
Please add an inbuilt functionality to edit the tags like Google provides in Gmail.

**Comment by ad1992** [comment]
@imjay009 I am little busy hence not getting time to build this. This is one of the tasks in our `TODO list`. Would be happy to recieve a pr on this.

**Comment by DevFlex** [comment]
@ad1992 if no one has taken on this issue yet I would like to help out.

**Comment by ad1992** [comment]
@DevFlex please go ahead 👍

**Comment by ad1992** [comment]
@DevFlex are you picking this up ?

**Comment by DevFlex** [comment]
yes if no one else wants it I would love to work on it. I just haven't really had a chance to because I got side tracked so hopefully this weekend I can work on it

**Comment by ad1992** [comment]
@DevFlex looking forward to your pr :) Please go ahead. Let me know if you need any help.

**Comment by DevFlex** [comment]
@ad1992 hey I got some work done on it tonight, but after I worked on it a little I started to question my approach a bit. I have just added some functionality to the handleTagClick function to set the focus on the input and change it's value to that of the tag clicked so it can be changed, but I am still thinking about the best way to update that specific tag's content say if they then choose to click on a suggestion so it doesn't default to adding a new tag and just altering the one they are editing.

**Comment by ad1992** [comment]
@DevFlex yes when user clicks on the tag to edit it should have all the functionalities which are there when user creates a tag. If you have started to work on it you can create a PR with (WIP) so I can have a look at it and we can discuss the approach then.

**Comment by ad1992** [comment]
@DevFlex any updates ?
