### ISSUE TITLE
Can't set browser autocomplete to "off"

### ISSUE THREAD

**Issue by malcolmvr** [react-tags/react-tags#461]
The browser's built-in autocomplete functionality is interfering. I need to be able to add the attribute `autocomplete="off"` to the `input`. I haven't seen any way to do this in the documentation and the code doesn't look like a method is provided. Could this please be added?

**Comment by khoramshahy** [comment]
hi
stale is not a good reason to close a bug
I also have this problem. 
![browser **autocomplete](https://user-images.githubusercontent.com/20140668/70690101-3452c580-1ccb-11ea-9ca6-8c04e49a2960.png)**

**Comment by khoramshahy** [comment]
Hi in the file ReactTags.js in the section where input element is created I add autoComplete: 'off' and that worked
my code is now like this: 
`var tagInput = !this.props.readOnly ? _react2.default.createElement(
        'div',
        { className: this.state.classNames.tagInput },
        _react2.default.createElement('input', {
          ref: function ref(input) {
            _this4.textInput = input;
          },
          className: this.state.classNames.tagInputField,
          type: 'text',
          placeholder: placeholder,
          'aria-label': placeholder,
          onFocus: this.handleFocus,
          onBlur: this.handleBlur,
          onChange: this.handleChange,
          onKeyDown: this.handleKeyDown,
          onPaste: this.handlePaste,
          name: inputName,
          id: inputId,
          maxLength: maxLength,
          value: this.props.inputValue,
          autoComplete: 'off' //I added this line
        }),
`

**Comment by tabna** [comment]
Is the solution ever going to be added to the repo?

**Comment by ad1992** [comment]
closed via #726, this will be available in the next version 🎉
