### ISSUE TITLE
Add "Clear tag" button

### ISSUE THREAD

**Issue by Kanosakl** [react-tags/react-tags#538]
I have find that this tag input system is useful for manipulating 1 tag at a time for filter/sorting purposes, but I find that it lacks a "clear tag" feature to remove all the tag.

**Comment by ad1992** [comment]
@Kanosakl would you like to give a PR for this ?

**Comment by one89** [comment]
Just submitted a PR for this :)

**Comment by SBagaria2710** [comment]
Is it still open? @ad1992

**Comment by ad1992** [comment]
@SBagaria2710 thanks for reminding on this, there is a PR for this, I will take a look at it and try wrapping it up this week
