### ISSUE TITLE
Add support for react-dnd 6+

### ISSUE THREAD

**Issue by mescarra** [react-tags/react-tags#547]
With these dependendencies:
```
   "react": "^16.8.6",
    "react-dnd": "^9.3.2",
    "react-dnd-html5-backend": "^9.3.2",
    "react-dom": "^16.8.6",
    "react-tag-input": "^6.4.0",
```
I'm getting:
```
TypeError: (0 , _reactDnd.DragDropContext) is not a function
./node_modules/react-materialui-tags/dist-modules/components/ReactTags.js
```

**Comment by KevinKelbie** [comment]
I'm getting this too with these dependancies: 

    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-tag-input": "^6.4.0",
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^3.0.2"

**Comment by KevinKelbie** [comment]
I got it working. Not sure how. All I did was stop `yarn` then `yarn run start` again. I hope this helps.

**Comment by jamalmoir** [comment]
Also getting this.

**Comment by ConnectedReasoning** [comment]
Same. KevinKelbies remedy did not help.

**Comment by ConnectedReasoning** [comment]
I had installed react-dnd -v 9.3.3 and  react-dnd-html5-backend -v 9.3.2

To fix I removed the newer versions of these packages and reinstalled with commands
yarn add react-dnd@5.0.0
yarn add react-dnd-html5-backend@3.0.2

**Comment by LennyLip** [comment]
"react-dnd": "5.0.0",
"react-dnd-html5-backend": "3.0.2",

should be placed in dependencies, not in devDependencies

**Comment by ad1992** [comment]
@LennyLip its part of dev and peer so that its not bundled with the library as these will increase the size of the library. Its mentioned in peer dependencies that 
```
"react-dnd": "^5.0.0",   
 "react-dnd-html5-backend": "^3.0.2",
```
So major version greater than these might not work @mescarra

**Comment by LennyLip** [comment]
@ad1992 Yes, I agree, but a user will get two react-dnd (If he wants react-dnd9 in his project) in any case. 

@mescarra you can try to use [name packages aliases](https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md#package-aliases)  in your project:

```
"dependencies": {
 "react-dnd": "^5.0.0",   
 "react-dnd-html5-backend": "^3.0.2",
 "react-dnd9": "react-dnd:^9.3.2",
 "react-dnd9-html5-backend": "^9.3.2",
}
```

**Comment by Belco90** [comment]
Just realized about those news peerDeps with v6 as I upgraded the package recently. Those peer deps don't make sense at all, they should be regular dependencies as the library completely depends on that: https://blog.angularindepth.com/npm-peer-dependencies-f843f3ac4e7f

With a peer dep you indicate your code is compatible with that, with a regular deep you indicate your code depends on that, and we have the latter here.

**Comment by demian85** [comment]
Can someone please understand that I need to use react-dnd 9.x but I cannot because this library requires react-dnd 5.x as a peer dependency. That's fucking outdated.
The author of this library maybe can explain what the hell crossed his mind when declaring peer dependencies...

**Comment by kgodey** [comment]
This error is because react-dnd 9.0 removed the DragDropContext decorator in favor of the new [DnDProvider component](https://react-dnd.github.io/react-dnd/docs/api/dnd-provider). This library needs to be updated to use the new component.

**Comment by ad1992** [comment]
I might not be able to pick this immediately. please feel free to PR.

**Comment by hirro** [comment]
Could this issue be renamed to add support for react-dnd 6+?

**Comment by hajnalben** [comment]
#566

**Comment by johnbowdenatfacet** [comment]
+1 to upgrade react-dnd, old version is using soon to be deprecated react lifecycle methods.

**Comment by Kesudan** [comment]
+1 to upgrade react-dnd as well! Love the tag input but we're having find alternatives as we already make use of latest react-dnd.

**Comment by razxssd** [comment]
+1 to upgrade react-dnd too

Same issue when using the last version of the library
