### ISSUE TITLE
How to prevent "Ctrl + V" from adding new tags

### ISSUE THREAD

**Issue by Nogias9x** [react-tags/react-tags#665]
Hello.

Thank you guys for this awesome lib.
I integrated it and things went well :+1: 
Then I realize it would be more convenient if users can paste from a clipboard, edit a bit then submit the tag. By now, when users  "Ctrl V", the tag will be added automatically.
Is there any way I could prevent that?

Thank you and have a nice day

**Comment by ad1992** [comment]
You are talking about something like https://github.com/prakhar1989/react-tags/pull/455 ?

**Comment by Nogias9x** [comment]
Thank you for looking up the PR @ad1992 ,

>You are talking about something like #455 ?

It seems to be. But I'm not familiar enough to know if it would prevent CtrlV from auto submitting or not.

Thank you and have a wonderful day :)

**Comment by jontycool** [comment]
I went through the PR but couldn't determine if this is what would help me. 
@ad1992 : can you provide your input or guide me in the right direction ?

**Comment by ad1992** [comment]
@jontycool what are you looking for, could you elaborate?

**Comment by jontycool** [comment]
Currently when users do "Ctrl + V" and paste something in the input field, it creates a tag automatically. Is there any way to stop it so that the user can edit the pasted content and then click Enter or "," or any other delimiter key to create the tag.

**Comment by jontycool** [comment]
@ad1992 : I know you might be busy, but any help on this issue would be very helpful.

**Comment by jontycool** [comment]
@Nogias9x : Any chance, you have managed to bypass this ?

**Comment by jontycool** [comment]
@Nogias9x : Hi, I dug deeper into the code a bit and I found this prop called "_allowAdditionFromPaste_". All you have to do is add this prop and set it to false. This will solve this particular issue.

@ad1992 : I think you can close this issue now.

**Comment by ad1992** [comment]
@jontycool glad to know that `allowAdditionFromPaste` will resolve the requirement but we should definitely document it so its not a hidden prop anymore. Will close once its documented. Thanks a lot for pointing this out!

**Comment by Nogias9x** [comment]
Awesome @ad1992 !
Thank you so much for the work <3
