### ISSUE TITLE
Module not found: Can't resolve 'react-dnd'

### ISSUE THREAD

**Issue by mayuriih** [react-tags/react-tags#673]
After installing it's giving me error like below

Module not found: Can't resolve 'react-dnd'

[Error: ENOENT: no such file or directory, stat '/initrd.img'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/initrd.img'
}

Dependencies:-
    "react": "^16.4.2",
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^3.0.2",
    "react-dnd-test-backend": "^3.0.2",
    "react-dom": "^16.4.2",

npm version:- 6.14.4

I tried to uninstall npm few times and reinstall it but it's giving me same error.

**Comment by ToxicToast** [comment]
try to install the missing packages?
