### ISSUE TITLE
Drop tag causes error: Invariant Violation: Expected to find a valid target at DragDropMonitorImpl.canDropOnTarget

### ISSUE THREAD

**Issue by johnvincentio** [react-tags/react-tags#690]
Drag is fine.
On drop, error is:

invariant.esm.js:29 Uncaught Invariant Violation: Expected to find a valid target.
    at invariant (http://localhost:8065/vendors-node_modules_date-io_moment_build_index_esm_js-node_modules_material-ui_core_esm_Card-277f99.bundle.js:9670:15)
    at DragDropMonitorImpl.canDropOnTarget (http://localhost:8065/vendors-node_modules_date-io_moment_build_index_esm_js-node_modules_material-ui_core_esm_Card-277f99.bundle.js:10106:70)
    at http://localhost:8065/vendors-node_modules_date-io_moment_build_index_esm_js-node_modules_material-ui_core_esm_Card-277f99.bundle.js:26017:30
    at Array.some (<anonymous>)
    at HTML5BackendImpl.handleTopDragOver (http://localhost:8065/vendors-node_modules_date-io_moment_build_index_esm_js-node_modules_material-ui_core_esm_Card-277f99.bundle.js:26016:47)

**Comment by johnvincentio** [comment]
It should be noted that I used:

"react-dnd": "^11.1.3",
"react-dnd-html5-backend": "^11.1.3"

which I have seen are not supported.

**Comment by johnvincentio** [comment]
However, the error  is caused by ReactTags.js, about line 251

return tags.map((tag, index) => (
  <Tag
  key={`${tag.id}-${index}`}

Notice 'index' being used in the key. This is the problem.

**Comment by johnvincentio** [comment]
Solution: ReactTags.js, about line 251

return tags.map((tag, index) => (
<Tag
key={${tag.id}}

and ensure tag.id is truly unique (use uuid() or similar).

**Comment by johnvincentio** [comment]
Further, due to the need for a hook, I introduced an intermediary. Code follows:

import React, { useRef } from 'react';
import PropTypes from 'prop-types';

import { createDndContext, DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';

import ReactTags from '../tags/ReactTags';

const TaskTag = props => {

	const renderTag = () => 
		 (
			<ReactTags
				id={props.id}
				inputFieldPosition={props.inputFieldPosition}
				tags={props.tags}
				suggestions={props.suggestions}
				minQueryLength={props.minQueryLength}
				autocomplete={props.autocomplete}
				handleDelete={props.handleDelete}
				handleAddition={props.handleAddition}
				handleDrag={props.handleDrag}
			/>
		)

	const DndContext = createDndContext(HTML5Backend);
	const managerRef = useRef(DndContext);

	return (
		<DndProvider backend={HTML5Backend} manager={managerRef.current.dragDropManager}>
			{renderTag()}
		</DndProvider>
	);
}

**Comment by johnvincentio** [comment]
Hopefully, this will be helpful...

**Comment by mrdannael** [comment]
Awesome, thanks for the input!

**Comment by johnvincentio** [comment]
Actually, upon review, I did rather more. 

I created a [react-tags](https://github.com/johnvincentio/react-tags) repo to allow for easier sharing.
