### ISSUE TITLE
Update react peer dependency to 17

### ISSUE THREAD

**Issue by Cherviakov** [react-tags/react-tags#693]
Currently this package still specify peer dependency react16, but react17 already out, please update package to be used with it.

**Comment by ad1992** [comment]
@Cherviakov want to take it up?

**Comment by Cherviakov** [comment]
Alright, will check it out.

**Comment by WhoIsDT** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.1" from react-tag-input@6.5.4
npm ERR! node_modules/react-tag-input
npm ERR!   react-tag-input@"*" from the root project
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by ad1992** [comment]
Sorry keeping this issue for so long, I will try fixing it this weeked

**Comment by apepper** [comment]
@ad1992 Thank you for your fix.

But the pre-dependencies `react-dnd` and `react-dnd-html5-backend` in the given version do not support React (officially):

https://github.com/react-tags/react-tags/blob/ee727fd6e417b27252581d502dbd4d15deff8193/package.json#L32-L35

Could you upgrade `react-dnd` and `react-dnd-html5-backend` to a more recent version?

I also noticed, that the specific version of `react-dom` is tied to `17.0.2`:

https://github.com/react-tags/react-tags/blob/ee727fd6e417b27252581d502dbd4d15deff8193/package.json#L36

It would be great, if `react-dom` version would be `^17.0.2` (identical to `react`).

**Comment by apepper** [comment]
In a blank folder this looks like this:

```
npm i react@17 react-tag-input
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17" from the root project
npm ERR!   peer react@"^17.0.2" from react-tag-input@6.6.1
npm ERR!   node_modules/react-tag-input
npm ERR!     react-tag-input@"*" from the root project
npm ERR!   2 more (react-dnd, react-dom)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from recompose@0.27.1
npm ERR! node_modules/react-dnd/node_modules/recompose
npm ERR!   recompose@"^0.27.1" from react-dnd@5.0.0
npm ERR!   node_modules/react-dnd
npm ERR!     peer react-dnd@"^5.0.0" from react-tag-input@6.6.1
npm ERR!     node_modules/react-tag-input
npm ERR!       react-tag-input@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution
```

**Comment by ad1992** [comment]
@apepper yeah soon will update the react-dnd as well (in next release), 
> It would be great if react-dom version would be ^17.0.2 (identical to react).

My bad, yeah will release a patch version for this, thanks for pointing this out.

> In a blank folder this looks like this:

You mean its not working for you?

**Comment by apepper** [comment]
> You mean its not working for you?

It means, that `npm` version 7 will fail installing both `react-tag-input` and `react` (version 17). This is because the sub-dependency `react-dnd` (version 5) does not officially work with `react` version 17.

### How to reproduce
* Create a new folder (e.g. `mkdir demo`)
* Switch into that folder (e.g. `cd demo/`)
* Try to install both `react` version 17 and `react-tag-input` using npm version 7 (e.g. `npm install react@17 react-tag-input`). Npm version 6 will not complain but (if I remember correctly) only print a warning.

### Expected
All works fine

### Actual

Npm fails to install with the following error message:

```
npm i react@17 react-tag-input
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17" from the root project
npm ERR!   peer react@"^17.0.2" from react-tag-input@6.6.1
npm ERR!   node_modules/react-tag-input
npm ERR!     react-tag-input@"*" from the root project
npm ERR!   2 more (react-dnd, react-dom)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from recompose@0.27.1
npm ERR! node_modules/react-dnd/node_modules/recompose
npm ERR!   recompose@"^0.27.1" from react-dnd@5.0.0
npm ERR!   node_modules/react-dnd
npm ERR!     peer react-dnd@"^5.0.0" from react-tag-input@6.6.1
npm ERR!     node_modules/react-tag-input
npm ERR!       react-tag-input@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution
```

**Comment by ad1992** [comment]
Ahh ok in the [example](https://stackblitz.com/edit/react-tag-input-1nelrc) it worked fine so didn't face this issue, once `react-dnd` is updated this will go off.
