### ISSUE TITLE
TypeError: (0 , _reactDnd.DragDropContext) is not a function

### ISSUE THREAD

**Issue by Humpkins** [react-tags/react-tags#696]
On /react-tag-input/dist-modules/components/ReactTags.js:574 

refer
#1513

571 | };
  572 | 
  573 | module.exports = {
  **574 |   WithContext: (0, _reactDnd.DragDropContext)(_reactDndHtml5Backend2.default)(ReactTags),**
  575 |   WithOutContext: ReactTags,
  576 |   KEYS: _constants.KEYS
  577 | };

**Comment by hjelmeir** [comment]
see https://github.com/prakhar1989/react-tags/issues/547 for some solutions, specifically setting specific package versions

```
yarn add react-dnd@5.0.0
yarn add react-dnd-html5-backend@3.0.2```
