### ISSUE TITLE
removeComponent props example

### ISSUE THREAD

**Issue by Pareder** [react-tags/react-tags#707]
[Current example](https://github.com/prakhar1989/react-tags#removecomponent-optional) in README for `removeComponent` prop has mistake. It is written that:
> The "ReactTags__remove" className and onClick handler properties can be automatically included

But you are passing not `onClick` but `onRemove` prop [here](https://github.com/prakhar1989/react-tags/blob/master/src/components/RemoveComponent.js#L26). So can you fix the documentation please?

And also in this example you are passing to native `button` element all possible props like [these](https://github.com/prakhar1989/react-tags/blob/master/src/components/RemoveComponent.js#L7), it may cause console error.

**Comment by ad1992** [comment]
thanks for pointing this out @Pareder, its fixed
