### ISSUE TITLE
Edge: pasting multiline text creates multiple tags

### ISSUE THREAD

**Issue by pietruszka** [react-tags/react-tags#721]
## Expected Behavior
Pasted multiline text creates only one tag.

Callback passed to `handleAddition` prop to be called once with a pasted text, e.g `{id: "word1\nword2\nword3", text: "word1\nword2\nword3"}`

## Current Behavior
Pasted multiline text creates multiple tags.

Callback passed to `handleAddition` prop to be called multiple times with a partial pasted text, e.g `{id: "word1", text: "word1"}`, `{id: "\n", text: "\n"}`, `{id: "\nword2", text: "\nword2"}`, `{id: "\nword3", text: "\nword3"}`

## Steps to Reproduce
1. Open React Tags Example (https://stackblitz.com/edit/react-tag-input-1nelrc) in Edge 90 / browserstack.com (Edge 90)
2. Paste multiline text
```
word1

word2



word3
```

**Comment by ad1992** [comment]
Looks like this bug specific to browser Edge, works fine in chrome, ff, and safari. @pietruszka want to create a PR?

**Comment by pietruszka** [comment]
> Looks like this bug specific to browser Edge, works fine in chrome, ff, and safari. @pietruszka want to create a PR?

Yes

**Comment by ad1992** [comment]
@pietruszka any update on this ?
