### ISSUE TITLE
Is there a way to disable the call of this.resetAndFocusInput() method after handleDelete action?

### ISSUE THREAD

**Issue by Adrian-CL** [react-tags/react-tags#722]
Currently I am mainly using this react-tag-input component for its removable tags feature.
The component itself is rich and user friendly, but I would like to hide the "Input Field" section during the usage.
So, when I have set the "inputFieldPosition" as hidden, "Uncaught TypeError: Cannot read property 'focus' of undefined" errors pop up because the page couldn't find the input field.

Please kindly advise. Thank you

**Comment by ad1992** [comment]
@Adrian-CL you need the removable tags feature but not allow the addition of tags?

**Comment by Adrian-CL** [comment]
Thanks for the rapid response.

And yes, that's correct. 
The tags will be inserted manually using a different method.

**Comment by Adrian-CL** [comment]
I have read it from here: https://npmdoc.github.io/node-npmdoc-react-tag-input/build/apidoc.html#apidoc.element.react-tag-input.WithContext.PropTypes.handleDelete
that the this.resetAndFocusInput() method is called after the handleDelete() method has done its business.

So I wonder if there is a way to disable it without changing the module itself.
It's a helpful mechanism but unfortunately not in my case. haha

**Comment by ad1992** [comment]
looks like you are trying in an older version, can you try out the latest version ? Or the [example](https://stackblitz.com/edit/react-tag-input-1nelrc), just hiding input field should work

**Comment by Adrian-CL** [comment]
I am currently using react-tag-input version 6.5.4, is there a newer version than this?
In your example, I can see the input field is not being focused after tag deletion. May I know how did you achieve that?

**Comment by ad1992** [comment]
@Adrian-CL [inputFieldPosition](https://github.com/react-tags/react-tags#inputfieldposition-optional-defaults-to-inline) can be only set to `top|bottom|inline`. `hidden` is an incorrect value. You can remove the `inputFieldPosition` and just hide the input field with css

**Comment by Adrian-CL** [comment]
@ad1992 thanks for your time and your assistance. 
I created a separate css and applied "visibility: hidden" to the class name ".ReactTags__tagInputField", now the input field is hidden and deleting tags doesn't throw error anymore.

Thank you once again!
