### ISSUE TITLE
Unique not working with autocomplete

### ISSUE THREAD

**Issue by Blackpinned** [react-tags/react-tags#728]
When I enabled autocomplete I was able to add the same tag multiple times by pressing the delimiter. Picking from the list still seems to work. I'm on version 6.6.1.

**Comment by ad1992** [comment]
@Blackpinned it works fine in [example](https://stackblitz.com/edit/react-tag-input-1nelrc), can you share a stackblitz example?

**Comment by Blackpinned** [comment]
Autocomplete wasn't enabled in the example. I enabled it and pressing "," allowed me to put Thailand in twice. 

https://stackblitz.com/edit/react-tag-input-r58jud?file=index.js

![image](https://user-images.githubusercontent.com/20385119/120614254-5314c100-c457-11eb-8b14-add232bf2cbc.png)

Added an image since I never used stackblitz before.

**Comment by ad1992** [comment]
@Blackpinned yeah, I can reproduce it now.
