### ISSUE TITLE
Functional component React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object

### ISSUE THREAD

**Issue by teo-jun-xiong** [react-tags/react-tags#757]
I'm currently using this package as such and recently encountered a bug.
```
import { WithContext as ReactTags }  from "react-tag-input";

const KeyCodes = {
  comma: 188,
  enter: 13,
};

const delimiters = [KeyCodes.comma, KeyCodes.enter];

const TagInput = ({ inputTags, inputSuggestions, setSelectedProjectCategories }) => {
  const [tags, setTags] = useState(inputTags);
  const [suggestions, setSuggestions] = useState(inputSuggestions);

  const handleDelete = (i) => {
    ...
  };

  const handleAddition = (tag) => {
    ...
  };

  return (
    <div className="tag-input">
      <ReactTags
        tags={tags}
        suggestions={suggestions}
        handleDelete={handleDelete}
        handleAddition={handleAddition}
        delimiters={delimiters}
        allowDragDrop={false}
      />
    </div>
  );
};

export default TagInput;

```
This is the error mesasge: 
```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at tag-input.js:38.
```
My peer dependencies are up to date:
```
"react": "^17.0.2",
"react-dnd": "^14.0.2",
"react-dnd-html5-backend": "^14.0.0",
"react-dom": "17.0.2"
```
Any advice on how to approach this? Thanks in advance!

**Comment by mattpetters** [comment]
getting a similar issue over on this one https://github.com/react-tags/react-tags/issues/751 seems to only happen on the minified build however

**Comment by ad1992** [comment]
@mattpetters  I verified it with the prod build as well and it works fine. I think some issue related to peer dependency might be causing this error so please make sure you have installed all the peer dependencies including the dependencies of peer dependencies correctly as that's what has changed in the latest version.
<img width="1387" alt="Screenshot 2021-07-01 at 1 09 24 PM" src="https://user-images.githubusercontent.com/11256141/124085715-f6b0bb80-da6d-11eb-832c-53fcfe2f94f3.png">

**Comment by ad1992** [comment]
closing this as this is not related to the library. feel free to reopen if you find the issue related to the library.
