### ISSUE TITLE
Uncaught TypeError: (0 , _reactDnd.useDrag) is not a function

### ISSUE THREAD

**Issue by abubakarakram167** [react-tags/react-tags#761]
I am using these packages in my current project below:
"react": "^17.0.1",
 "react-tag-input": "^6.7.1",
 "react-dnd": "^5.0.0",
 "react-dnd-html5-backend": "^3.0.2",
 
 Please can somebody help me with this issue?

**Comment by ad1992** [comment]
@abubakarakram167 you need to update the peer dependencies to make it work 👇🏻 
```
"react": "^17.0.2",
"react-dnd": "^14.0.2",
"react-dnd-html5-backend": "^14.0.0",
"react-dom": "17.0.2"
```

**Comment by abubakarakram167** [comment]
> @abubakarakram167 you need to update the peer dependencies to make it work 👇🏻
> 
> ```
> "react": "^17.0.2",
> "react-dnd": "^14.0.2",
> "react-dnd-html5-backend": "^14.0.0",
> "react-dom": "17.0.2"
> ```



Now after using these Packages i am getting that error:

Uncaught TypeError: Object(...) is not a function
    at Module../src/components/Root.prod.js (Root.prod.js:37)
    at __webpack_require__ (bootstrap:832)
    at fn (bootstrap:129)
    at Module../src/components/Root.js (Root.js:1)
    at __webpack_require__ (bootstrap:832)
    at fn (bootstrap:129)
    at Module../src/index.js (bundle.js:353738)
    at __webpack_require__ (bootstrap:832)
    at fn (bootstrap:129)
    at Object.0 (bundle.js:366501)
    
    
    And Root.prod.js file is below:
    
    
    
import React, { Component } from 'react'
import { Provider } from 'react-redux'
import { Router, browserHistory } from 'react-router'
import { syncHistoryWithStore } from 'react-router-redux'
import Piwik from 'helper/Piwik'
import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import routes from '../routes'

/**
 * Component is exported for conditional usage in Root.js
 */
class Root extends Component {
  render() {
    const { store } = this.props

    // Create an enhanced history that syncs navigation events with the store
    this.history = this.history || syncHistoryWithStore(browserHistory, store)

    // track this entry location because the current version of react router
    // doesn't work perfectly with the piwik tracker
    Piwik.track(window.location)

    return (
      /**
       * Provider is a component provided to us by the 'react-redux' bindings that
       * wraps our app - thus making the Redux store/state available to our 'connect()'
       * calls in component hierarchy below.
       */
      <Provider store={store}>
        <Router history={Piwik.connectToHistory(this.history)}>{routes}</Router>
      </Provider>
    )
  }
}

export default DragDropContext(HTML5Backend)(Root)

**Comment by ad1992** [comment]
Doesn't look like you are using the right way,You just need to use `UseContext` when using `react-tag-input`, you can check out the [demo](https://stackblitz.com/edit/react-tag-input-1nelrc)

**Comment by abubakarakram167** [comment]
> Doesn't look like you are using the right way,You just need to use `UseContext` when using `react-tag-input`, you can check out the [demo](https://stackblitz.com/edit/react-tag-input-1nelrc)

But i am getting error regarding using DragDropContext in the Root.prod.js after migrating to your mentioned packages.
I am not using React-tags-input in Prod.js file in which error is happening.

**Comment by abubakarakram167** [comment]
What if i remove using this DragDropContext(HTML5Backend)(Root). in the file .And just use only react tag input in file in which i want to use ?

**Comment by ad1992** [comment]
You need to update the API as per `react-dnd` , `react-dnd-html5-backend` as it doesn't expose `DragDropContext` and instead uses `DndProvider`, you can check the API https://react-dnd.github.io/react-dnd/docs/overview.

**Comment by ad1992** [comment]
closing this as its related the host App `react-dnd` and not `react-tag-input`. Feel free to reopen if you find any issue related to this library
