### ISSUE TITLE
ReactTag doesn't change at all after taking in className

### ISSUE THREAD

**Issue by ahl1395** [react-tags/react-tags#762]
Hey, apologies in advance if this is a dumb question.

But when I pass in a className to my ReactTagInput component, none of the corresponding CSS changes take effect.

**Here is my code:**
...
<ReactTagInput 
                    className="form__input"
                    tags={passions} 
                    onChange={(x) => setPassions(x)}
                    placeholder="What do you love to do?"
                  />
...

**And here is my CSS code:**
.form__input {
    margin-top: 10px;
    height: 47px;
    width: 375px;
    // width: 100%;
    font-weight: 500;
    color: #808080;
    padding: 0 22px;
    border-radius: 40px;
    border: 1px solid #D8D8D8;
    @include breakpoint(phone) {
      height: 56px;
      padding: 0 40px;
    }
    &.form__input--sm {
      height: 49px;
      padding: 0 28px;
    }
  }

**Here is a screenshot of the output**. Notice the ReactTagInput is completely different from the other input boxes surrounding it, even though they all take in the same CSS class (form__input):

<img width="436" alt="Screen Shot 2021-07-07 at 12 59 53 AM" src="https://user-images.githubusercontent.com/10375199/124702704-d4c89600-debe-11eb-8669-ef1e14a97ba1.png">

**Comment by ad1992** [comment]
@ahl1395 you will need to pass `classNames` object as shown [here](https://github.com/react-tags/react-tags#styling) based on your usecase.

**Comment by ahl1395** [comment]
@ad1992 Thank you for the response. I was able to edit certain parts of the CSS, but was unable to edit the border-radius to round out the input box. Do you know why this is?

Here's a screenshot (notice the border radius is 300px): 
<img width="1200" alt="Screen Shot 2021-07-07 at 8 56 26 PM" src="https://user-images.githubusercontent.com/10375199/124846106-16f8e280-df66-11eb-9791-4f57282c4516.png">

**Comment by ad1992** [comment]
@ahl1395 little unclear, you can always apply your CSS to the class as it doesn't come with any styling so you can directly update the CSS file.

**Comment by ahl1395** [comment]
@ad1992 Right, I understand that. Why doesn't updating the border-radius round out the border like it should?

**Comment by ad1992** [comment]
@ahl1395 do you mind sharing a code sandbox/stackblitz with the issue you are facing so I can look into it?

**Comment by ahl1395** [comment]
@ad1992 Here is a Code Sandbox that doesn't work: https://codesandbox.io/embed/zealous-haslett-418bm?fontsize=14&hidenavigation=1&theme=dark

Would you be able to simply adjust the border-radius of a ReactTagInput component so that the edges are rounded? I'd like to do a sanity check to make sure I'm not going crazy.

**Comment by ad1992** [comment]
@ahl1395 the above codesandbox throws error and looks like you are using a forked version of the library, 
However you can add `border-radius` to the `.ReactTags__selected span.ReactTags__tag` selector and it should work 
<img width="362" alt="Screenshot 2021-07-11 at 6 38 37 PM" src="https://user-images.githubusercontent.com/11256141/125196411-7cefad80-e277-11eb-827e-85885a99ec60.png">
Here is the  [working demo](https://react-tag-input-ojy8nu.stackblitz.io/)

**Comment by ahl1395** [comment]
@ad1992 you're a legend. Thanks for the help.
