### ISSUE TITLE
Update documentation for Hooks

### ISSUE THREAD

**Issue by masudhossain** [react-tags/react-tags#769]
I think it'll be very fruitful if you update the documentation to support hooks.

**Comment by ad1992** [comment]
@masudhossain what documentation do you suggest to add, can you elaborate?

**Comment by masudhossain** [comment]
@ad1992  the documentation currently shows how to use react-tags with class components. But most people now uses Hooks components. So updating it to hooks would be great.

**Comment by ad1992** [comment]
Yeah definitely we should do that 👍🏻
