### ISSUE TITLE
Error on refresh with Nextjs

### ISSUE THREAD

**Issue by bassiebangura** [react-tags/react-tags#795]
**Server Error**
### ReferenceError: onkeydown is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
pages/_document.tsx (11:31) @ Function.getInitialProps

   9 | class MyDocument extends Document {
  10 |   static async getInitialProps(ctx: DocumentContext) {
> 11 |     const initialProps = await Document.getInitialProps(ctx);
     |                               ^
  12 |     return { ...initialProps };
  13 |   }
  14 |

**Comment by alienself** [comment]
Same issue
