### ISSUE TITLE
inputFieldPosition doesn't change position of input and tags

### ISSUE THREAD

**Issue by J-pilon** [react-tags/react-tags#811]
Hi, I'm trying to change the position to inline but the tags remain above the input. Could someone help me with this issue?

import React, {useState} from "react";
import { WithContext as ReactTags } from "react-tag-input";

const KeyCodes = {
    comma: 188,
    enter: [10, 13],
};

const delimiters = [...KeyCodes.enter, KeyCodes.comma];

const MuliTagInput: React.FC = (props) => {
    const [ tagsState, setTagsState ] = useState({
        tags: [],
    });

    function handleDelete(i) {
        const { tags } = tagsState;
        setTagsState({
            tags: tags.filter((tag, index) => index !== i)
        });
    }

    function handleAddition(tag) {
        setTagsState(prev => ({
            tags: [...prev.tags, tag]
        }));
    }

    function handleDrag(tag, currPos, newPos) {
        const { tags } = tagsState;
        const newTags = tags.slice();

        newTags.splice(currPos, 1);
        newTags.splice(newPos, 0, tag);

        setTagsState({tags: newTags})
    }

    const { tags } = tagsState

    return (
        <div>
            <ReactTags
                placeholder="type here..."
                inputFieldPosition="inline"
                tags={tags}
                labelField="label"
                // suggestions={suggestions}
                handleDelete={handleDelete}
                handleAddition={handleAddition}
                handleDrag={handleDrag}
                delimiters={delimiters}
            />
        </div>
    );
}

export default MuliTagInput;

**Comment by ad1992** [comment]
@J-pilon looks like this got broken in the latest release, will look into this.

**Comment by ad1992** [comment]
This has been fixed, you can test it out in https://react-tag-input-1nelrc.stackblitz.io/
