### ISSUE TITLE
Ignore Suggestions

### ISSUE THREAD

**Issue by runabol** [react-tags/react-tags#888]
When using the suggestion feature, if I get a partial match on a suggestion I am forced to use the suggestion. e.g.: 

<img width="627" alt="Screen Shot 2022-11-17 at 2 49 58 PM" src="https://user-images.githubusercontent.com/3052806/202545145-1cb8a263-77af-4e59-b3fa-b2a1c9836931.png">

But what if I want to actually use the partial word (in this case "Child" vs. "Children"). I can't seem to be able to add "Child" as a new tag. When I hit Enter or `,` it selects "Children". Pressing the Escape button doesn't help either. It removes the suggestion but still picks it when I hit Enter.

**Comment by flobauer** [comment]
I think you can remove the `autocomplete` attribute and then it will not be used.

**Comment by ad1992** [comment]
As mentioned by @flobauer you can disable `autocomplete` to achieve the expected behavior. However, I think `autocomplete` prop is confusing and we should probably remove the prop altogether as its not intuitive
