### ISSUE TITLE
Add support for max number of tags allowed

### ISSUE THREAD

**Issue by timothytong** [react-tags/react-tags#920]
When the user has created X number of tags (x defined in a prop), hide the input so that the user can no longer create more tags. Unhide the input once one of the tags has been removed (number of tags < limit)

**Comment by faizanu94** [comment]
This is implemented in https://github.com/react-tags/react-tags/pull/933 and available for review @ad1992

**Comment by ad1992** [comment]
closed by https://github.com/react-tags/react-tags/pull/933
