### ISSUE TITLE
Add Semantic pull request GitHub Action

### ISSUE THREAD

**Issue by ad1992** [react-tags/react-tags#927]
https://github.com/amannn/action-semantic-pull-request

**Comment by sr2706** [comment]
Hey @ad1992 . Can you assign this issue to me, if unassigned?

**Comment by ad1992** [comment]
@sr2706 sure go ahead!

**Comment by sr2706** [comment]
Thank you, I have added the Github Action and created a pull request. Can you review

**Comment by ad1992** [comment]
closed via https://github.com/react-tags/react-tags/pull/929
