### ISSUE TITLE
How can I copy paste tags?

### ISSUE THREAD

**Issue by ErlanBazarov** [react-tags/react-tags#954]

**Comment by ad1992** [comment]
@ErlanBazarov you mean copying existing tags and pasting it back ?

**Comment by ErlanBazarov** [comment]
Mostly I just need to paste multiple tags copied from a text. Let's say I have text: "fruit, vegetable, machine". I want to paste them to ReactTags together without having to type/copy them one by one

**Comment by ad1992** [comment]
Sure you can do that, you need to pass `allowAdditonFromPaste` as `true` and pass the comma key code in delimiters as well. You can check out the working [example](https://stackblitz.com/edit/react-tag-input-1nelrc?file=index.js)

**Comment by ad1992** [comment]
@ErlanBazarov I hope this is working for you now so closing. Incase if it doesn't feel free to reopen
