### ISSUE TITLE
react-tags breaks default dnd behaviour

### ISSUE THREAD

**Issue by twltwl** [react-tags/react-tags#98]
I have an input field which I drag images to in my application. After adding tags to my application this no longer works.

demo: http://www.webpackbin.com/4Jji1CstZ

**Comment by prakhar1989** [comment]
Hey! Thanks for raising this issue and creating the webpackbin link. However, I'm not sure if I'm able to replicate the issue. I removed `<Tags>` and I still couldn't see any difference with the image being dragged. Could you please clarify what exactly should I be expecting to see?

Thanks!

**Comment by twltwl** [comment]
Im dragging the image into the input field. After adding a tag this is not possible anymore.
I created a gif showing how to reproduce it -> http://imgur.com/a/CRkLv

**Comment by ad1992** [comment]
@twltwl does this issue happen v5.0.1 ?

**Comment by ad1992** [comment]
this should be fixed via https://github.com/react-tags/react-tags/issues/637, feel free to reopen if it still persists.
The fix will be released in the next version.
