### ISSUE TITLE
An Extra Tag is Created for the Last Letter When Typing in Korean

### ISSUE THREAD

**Issue by ABlued** [react-tags/react-tags#988]
When typing in Korean, an extra tag is created for the last letter.

https://github.com/user-attachments/assets/2f542235-250f-4666-8f0d-17263cd0fca6

I believe the issue is likely caused by the onKeyDown event. Changing the event handler from `onKeyDown` to `onKeyUp` resolves the bug, 

```
src/components/ReactTag.tsx 512~532
  <input
        {...inputProps}
        ref={(input) => {
          textInput.current = input;
        }}
        className={allClassNames.tagInputField}
        type="text"
        placeholder={placeholder}
        aria-label={placeholder}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onChange={handleChange}
        onKeyUp={handleKeyDown} // onKeyDown -> onKeyUp
        onPaste={handlePaste}
        name={inputName}
        id={inputId}
        maxLength={maxLength}
        value={inputValue}
        data-automation="input"
        data-testid="input"
      />
```

Results after modifying the code

https://github.com/user-attachments/assets/f25163c3-bdc3-4a42-ab83-d6ad27bcdf0d

but it also introduces side effects that break many of the tests.🥲
Can you solve the bug for this?

**Comment by ad1992** [comment]
Hi @ABlued , thank you for reporting this, will soon look into this.

**Comment by shrilakshmishastry** [comment]
@ad1992 can I inspect more on this?

**Comment by ad1992** [comment]
> @ad1992 can I inspect more on this?

Sure, please go ahead @shrilakshmishastry

**Comment by shrilakshmishastry** [comment]
this issue is similar to https://github.com/vuejs/vue/issues/10277

**Comment by ad1992** [comment]
@ABlued could you confirm if its fixed in https://react-tags-git-fork-shrilakshmishastry-fix-on-4626e5-react-tags.vercel.app/ ?

**Comment by ABlued** [comment]
@ad1992 The issue has been completely resolved! You solved it with `nativeEvent.isComposing`. Thank you for sharing the solution! 👍

**Comment by ad1992** [comment]
> @ad1992 The issue has been completely resolved! You solved it with `nativeEvent.isComposing`. Thank you for sharing the solution! 👍

Awesome! Thanks for testing it out confirming the fix. Thanks to @shrilakshmishastry for pushing the fix ✨
